trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  phpVersion: '8.2'

steps:
  - checkout: self

  - script: |
    sudo add-apt-repository ppa:ondrej/php -y
    sudo apt-get update
    sudo apt-get install -y php8.2 php8.2-cli php8.2-mbstring php8.2-xml php8.2-zip php8.2-bcmath php8.2-intl php8.2-curl
    sudo update-alternatives --set php /usr/bin/php8.2
    php -v
  displayName: 'Install PHP 8.2 and extensions'

  - script: |
      composer install --no-interaction --prefer-dist
    displayName: 'Install Composer dependencies'

  - script: |
      ./vendor/bin/phpunit --configuration phpunit.xml --log-junit test-results.xml
    displayName: 'Run PHPUnit tests and generate test report'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test-results.xml'
      failTaskOnFailedTests: true
    condition: succeededOrFailed()
    displayName: 'Publish Test Results'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/php-app.zip'
      replaceExistingArchive: true
    displayName: 'Archive PHP app'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish build artifacts'
