trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  phpVersion: '8.2'

steps:
  - checkout: self

  # Install PHP 8.2 and required extensions
  - script: |
      sudo add-apt-repository ppa:ondrej/php -y
      sudo apt-get update
      sudo apt-get install -y php8.2 php8.2-cli php8.2-mbstring php8.2-xml php8.2-zip php8.2-bcmath php8.2-intl php8.2-curl
      sudo update-alternatives --install /usr/bin/php php /usr/bin/php8.2 100
      sudo update-alternatives --install /usr/bin/php-config php-config /usr/bin/php-config8.2 100
      sudo update-alternatives --install /usr/bin/phpize phpize /usr/bin/phpize8.2 100
      php -v
    displayName: 'Install and switch to PHP 8.2'

  # Install Composer
  - script: |
      curl -sS https://getcomposer.org/installer | php
      sudo mv composer.phar /usr/local/bin/composer
      php /usr/local/bin/composer --version
    displayName: 'Install Composer'

  # Install Composer dependencies using PHP 8.2
  - script: |
      php -v
      php /usr/local/bin/composer install --no-interaction --prefer-dist
    displayName: 'Install Composer dependencies'

  # Run PHPUnit tests
  - script: |
      ./vendor/bin/phpunit --configuration phpunit.xml
    displayName: 'Run PHPUnit tests'

  # Package app and deployment script
  - script: |
      # Create a zip file of the app excluding git and existing zip files
      zip -r myapp.zip . -x "*.git*" "*.zip"
      mv myapp.zip $(Build.ArtifactStagingDirectory)/
      # Include the deploy script
      cp deploy-linux.sh $(Build.ArtifactStagingDirectory)/
    displayName: 'Package app and deploy script'

  # Publish build artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish build artifacts'

  # Download build artifact for deployment
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: 'drop'
      targetPath: '$(Pipeline.Workspace)/drop'
    displayName: 'Download Build Artifact'

  # Deploy to Linux VM using SSH
  - task: SSH@0
    inputs:
      sshEndpoint: 'Linux-vm-ssh'  # The SSH service connection name
      runOptions: 'commands'
      commands: |
        # Stop Apache
        sudo systemctl stop apache2
        # Clean existing files and unzip new ones
        sudo rm -rf /var/www/html/*
        unzip -o $(Pipeline.Workspace)/drop/myapp.zip -d /var/www/html/
        # Restart Apache
        sudo systemctl start apache2
        # Run a smoke test to verify deployment
        curl -I http://localhost | grep "200 OK" || {
          echo "❌ Smoke test failed"
          exit 1
        }
        echo "✅ Deployment complete."
    displayName: 'Deploy to Linux VM and restart Apache'
