trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  phpVersion: '8.2'

steps:
  - checkout: self

  - script: |
      sudo add-apt-repository ppa:ondrej/php -y
      sudo apt-get update
      sudo apt-get install -y php${phpVersion} php-cli php-mbstring php-xml php-zip php-bcmath php-intl php-curl unzip
      php -v
    displayName: 'Install PHP $(phpVersion) and extensions'

  - script: |
      composer install --no-interaction --prefer-dist
    displayName: 'Install Composer dependencies'

  - script: |
      ./vendor/bin/phpunit --configuration phpunit.xml --log-junit test-results.xml
    displayName: 'Run PHPUnit tests and generate test report'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test-results.xml'
      failTaskOnFailedTests: true
    condition: succeededOrFailed()
    displayName: 'Publish Test Results'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/php-app.zip'
      replaceExistingArchive: true
    displayName: 'Archive PHP app'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish build artifacts'
