trigger:
  branches:
    include:
      - main

pool:
  name: IISAgentPool  # Use the agent pool for IIS machines
  demands:
    - agent.os -equals Windows_NT  # Ensure the agent is running on Windows

variables:
  phpVersion: '8.2'

steps:
  # Checkout the code from the repository
  - checkout: self

  # Verify PHP installation (assuming PHP is installed manually)
  - script: |
      php -v
    displayName: 'Verify PHP Installation'

  # Install Composer (Windows version)
  - script: |
      echo "Installing Composer..."
      php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      php composer-setup.php
      php -r "unlink('composer-setup.php');"
      php composer.phar --version
    displayName: 'Install Composer'

  # Install Composer dependencies using PHP 8.2
  - script: |
      echo "Installing Composer dependencies..."
      php composer.phar install --no-interaction --prefer-dist
    displayName: 'Install Composer dependencies'

  # Run PHPUnit tests
  - script: |
      echo "Running PHPUnit tests..."
      ./vendor/bin/phpunit --configuration phpunit.xml
    displayName: 'Run PHPUnit tests'

  # Package app and deployment script
  - script: |
      echo "Creating zip of app..."
      powershell Compress-Archive -Path * -Exclude *.git*,*.zip -DestinationPath $(Build.ArtifactStagingDirectory)\myapp.zip
      echo "Copying deploy script..."
      copy deploy.bat $(Build.ArtifactStagingDirectory)\deploy.bat
    displayName: 'Package app and deploy script'

  # Check contents of Artifact Staging Directory
  - script: |
      echo "Checking contents of Artifact Staging Directory..."
      dir $(Build.ArtifactStagingDirectory)
    displayName: 'Check contents of Artifact Staging Directory'

  # Publish build artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish build artifacts'

  # Download build artifact for deployment
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: 'drop'
      targetPath: '$(Pipeline.Workspace)/drop'
    displayName: 'Download Build Artifact'

  # Check downloaded build artifacts
  - script: |
      echo "Checking downloaded artifacts..."
      dir $(Pipeline.Workspace)/drop
    displayName: 'Check downloaded artifacts'

  # Upload build artifacts to the IIS server
  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'IIS-vm-ssh'  # This should be your Windows IIS endpoint
      sourceFolder: '$(Pipeline.Workspace)/drop'
      contents: '**'
      targetFolder: 'C:\\inetpub\\wwwroot\\MyWebApp'  # IIS root directory
    displayName: 'Copy build artifacts to IIS'

  # Verify files on the IIS server
  - task: SSH@0
    inputs:
      sshEndpoint: 'IIS-vm-ssh'
      runOptions: 'inline'
      inline: |
        echo "Checking contents of C:\\inetpub\\wwwroot\\MyWebApp:"
        dir C:\\inetpub\\wwwroot\\MyWebApp
    displayName: 'Verify files on IIS server'

  # Run the deploy.bat script to deploy the app
  - script: |
      echo Running deploy.bat...
      call $(Pipeline.Workspace)/drop/deploy.bat
    displayName: 'Run deployment script'
