trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  phpVersion: '8.2'

steps:
  - checkout: self

  - script: |
      sudo add-apt-repository ppa:ondrej/php -y
      sudo apt-get update
      sudo apt-get install -y php${phpVersion} php${phpVersion}-cli php${phpVersion}-mbstring php${phpVersion}-xml php${phpVersion}-zip php${phpVersion}-bcmath php${phpVersion}-intl php${phpVersion}-curl
      sudo update-alternatives --set php /usr/bin/php${phpVersion}
      php -v
    displayName: 'Install PHP ${phpVersion} and extensions'

  - script: |
      composer install --no-interaction --prefer-dist
    displayName: 'Install Composer dependencies'

  - script: |
      ./vendor/bin/phpunit --configuration phpunit.xml
    displayName: 'Run PHPUnit tests'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: '**/*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy files to artifact staging'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish build artifacts'
